import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar/Navbar';
import Footer from './components/Footer/Footer';
import UserData from './components/UserActivity/UserData';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Diabolo4.life',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="md:flex w-[95%] mx-auto mt-3">
          <div className="md:w-[80%] mr-2  mt-[7rem]">{children}</div>
          <div className="md:w-[20%]">
            <UserData />
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
